print("BIOLOGY TEST")
print("Enter in order the stages of human development:")
driopithecus = input()
ramapithecus = input()
australopithecine = input()
homo_habilis = input() 
homo_erectus = input() 
paleoanthropist = input()
homo_sapiens = input()
print("Introduced stages of human development:")
print(driopithecus, ramapithecus, australopithecine, homo_habilis, homo_erectus, paleoanthropist, homo_sapiens, sep = " => ")